import React from 'react';
import Icon from './Icon.jsx';
import { workspaceSavedLabel } from '../format.js';

const status = c => c.unavailable || c.status === 'needs-recovery' ? 'Needs recovery' : c.status === 'analyzing' ? 'Analyzing' : c.status === 'needs-analysis' ? 'New evidence' : c.reviewed ? 'Reviewed' : c.revisionCount ? 'Ready for review' : 'Getting started';

export default function HomeDesk({cases, loading, busy, hasExample, preparedExample, preparedError, onPreparedRetry, onPrepared, modelNotice, onCreate, onExample, onOpen, onRefresh, error, listError, onDismiss}) {
  return <>
    <section className="desk-intro">
      <div className="desk-intro-copy"><span className="intro-label"><span className="status-dot"/>California wage review</span><h1>Your work.<br/>On the record.</h1><p>Understand a new pay correction.<br/>Prepare the factual update, with its evidence.</p></div>
      <div className="intro-action"><div className="proof-symbol" aria-hidden="true"><svg viewBox="0 0 160 160" fill="none"><path d="M25 32h48v48H25zM87 80h48v48H87z" stroke="currentColor" strokeWidth="9"/><path d="M54 55h52v52H54z" fill="currentColor"/><path d="m67 80 11 11 20-23" stroke="#3153ed" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round"/></svg></div><button className="button hero-button" onClick={onCreate}>Start a case<Icon name="plus" size={21}/></button><span>Begin with the records you have.</span>{preparedExample?.available&&<button type="button" className="hero-example" onClick={onPrepared}>Inspect the prepared example</button>}</div>
    </section>
    {error && <div className="notice error" role="alert"><Icon name="alert"/><div>{error}</div><button className="icon-button" aria-label="Dismiss error" onClick={onDismiss}><Icon name="close"/></button></div>}
    <section className="example-entry" aria-labelledby="example-entry-title">
      <div className="prepared-entry"><span className="eyebrow">Fictional case · recorded results</span><h2 id="example-entry-title">See a complete case, with its evidence.</h2><p>Inspect the saved accounts, follow the original sources and download a factual update. No Codex setup or model call is needed to explore it.</p>{preparedExample?.available?<button type="button" className="button secondary" onClick={onPrepared}>Inspect the prepared example<Icon name="arrow" size={17}/></button>:<div className="prepared-entry-unavailable"><p role={preparedError?'status':undefined}>{preparedError?'The prepared example could not be loaded. Your workspaces remain available.':preparedExample?'This local package does not include the prepared example.':'Checking for the prepared example…'}</p>{(preparedError||preparedExample)&&<button type="button" className="text-button" onClick={onPreparedRetry}>Check again</button>}</div>}</div>
      {hasExample&&<div className="fresh-entry"><h3>Try a fresh analysis</h3><p>Create a separate fictional workspace and import the starting records. You choose when to analyze them using the configured model service.</p><button type="button" className="text-button" disabled={!!busy} onClick={onExample}>{busy==='example'?'Creating workspace…':'Start the example afresh'}<Icon name="plus" size={16}/></button><p className="entry-model-note">{modelNotice}</p></div>}
    </section>
    <div className="desk-grid">
      <section className="workspace-list"><div className="section-title"><div className="desk-title"><h2>Your case desk</h2><span className="desk-count">{cases.length}</span></div><button className="text-button" onClick={onRefresh}><Icon name="refresh" size={15}/>Refresh</button></div>
        {listError && <div className="notice error" role="alert">{listError}<button className="text-button" onClick={onRefresh}>Try again</button></div>}
        {loading ? <div className="loading-text"><span className="spinner"/>Opening your workspaces…</div> : cases.length ? <div className="case-table">{cases.map(c=><button key={c.id} onClick={()=>onOpen(c.id)} className="case-table-row"><span className="case-file-icon"><Icon name="folder" size={24}/></span><span className="case-row-main"><strong>{c.title}</strong>{c.unavailable?<span className="case-recovery-message">{c.message||'The saved case cannot be read. Original files are preserved.'}</span>:<><span>{c.exampleId?'Fictional workspace · ':''}{c.employer || 'Employer not yet named'}</span><span className="case-record-count">{c.sourceCount} {c.sourceCount===1?'record':'records'} · {c.revisionCount} {c.revisionCount===1?'revision':'revisions'}</span><span className="case-saved">{workspaceSavedLabel(c,cases)}</span></>}</span><span className={`badge ${c.unavailable?'attention':c.reviewed?'good':c.revisionCount?'attention':'neutral'}`}>{status(c)}</span><span className="row-arrow"><Icon name="arrow"/></span></button>)}</div> : <div className="first-case"><Icon name="folder" size={32}/><h3>A place for your side of the story.</h3><p>Add a pay record, an employer response, or an account of a conversation. You can leave missing facts open.</p><button className="button secondary" onClick={onCreate}>Create your first case<Icon name="plus"/></button></div>}
      </section>
      <aside className="workflow-guide" id="how-it-works"><div className="section-title"><h2>A clearer account</h2><Icon name="link" size={19}/></div><ol><li><span>1</span><div><h3>Bring the records together</h3><p>Original files and your attributed account stay intact.</p></div></li><li><span>2</span><div><h3>See what actually changed</h3><p>Inspect the source behind each interpretation. Correct anything that needs it.</p></div></li><li><span>3</span><div><h3>Review the next step</h3><p>Keep open questions visible in a factual case update.</p></div></li></ol><div className="workflow-note"><Icon name="lock" size={17}/><p>Your review stays in your hands.<br/>Nothing is filed or sent from here.</p></div></aside>
    </div>
    <footer className="home-footer"><span>WageProof prepares factual case updates. It does not determine legal rights.</span><span>Stored locally. Analysis uses the configured model service.</span></footer>
  </>;
}
