import React,{useState,useEffect,useCallback,useRef} from 'react';
import {api,post} from './api.js';
import {moneyRange,dateTime,words,workspaceSavedLabel} from './format.js';
import Icon from './components/Icon.jsx';
import Dialog from './components/Dialog.jsx';
import SourceDrawer from './components/SourceDrawer.jsx';
import ReviewEditor from './components/ReviewEditor.jsx';
import HomeDesk from './components/HomeDesk.jsx';
import CreateCase from './components/CreateCase.jsx';
import ReviewConfirm from './components/ReviewConfirm.jsx';
import CaseOverview from './components/CaseOverview.jsx';
import PaymentDecision from './components/PaymentDecision.jsx';
import PrepareUpdate from './components/PrepareUpdate.jsx';
import RequestDraftDialog from './components/RequestDraftDialog.jsx';
import './experience.css';
const caseFromHash=()=>window.location.hash.match(/^#\/case\/([^/?]+)/)?.[1]||null;
const tabFromHash=()=>new URLSearchParams(window.location.hash.split('?')[1]||'').get('view')==='sources'?'sources':'review';
const isReviewed=r=>Boolean(r?.review?.at||r?.review?.status==='reviewed');
function claimStageLabel(record,revision){if(revision?.analysis){const reported=revision.analysis.caseContext?.claimStatus;return reported==='pending'?'Pending claim · reported':reported==='not_filed'?'Before filing · reported':'Stage not established'}const stage=record.context?.stage;return stage==='pending-claim'?'Pending claim':stage==='no-claim'?'Before filing':'Stage not established'}
function ErrorBox({message,onRetry,onDismiss}){return <div className="notice error" role="alert"><Icon name="alert"/><div>{message}{onRetry&&<button className="text-button" onClick={onRetry}>Try again</button>}</div>{onDismiss&&<button className="icon-button" aria-label="Dismiss error" onClick={onDismiss}><Icon name="close"/></button>}</div>}
function Badge({children,tone='neutral'}){return <span className={`badge ${tone}`}>{children}</span>}
function Empty({icon='file',title,children,action}){return <div className="empty-state"><div className="empty-icon"><Icon name={icon} size={29}/></div><h3>{title}</h3><p>{children}</p>{action}</div>}
function Logo({onClick}){return <button className="brand" onClick={onClick} aria-label="WageProof cases"><span className="brand-mark"><svg viewBox="0 0 36 36" fill="none" aria-hidden="true"><path d="M3 4h15v15H3zM18 17h15v15H18z" stroke="currentColor" strokeWidth="3"/><path d="M10 11h16v15H10z" fill="currentColor"/><path d="m13 18 4 4 7-9" stroke="white" strokeWidth="2"/></svg></span><span>WageProof<span className="brand-period">.</span></span></button>}
function RecordUpload({caseRecord,busy,uploading,onUpload,onNote}){const [files,setFiles]=useState([]);const [kind,setKind]=useState('evidence');const [noteTitle,setNoteTitle]=useState('Worker account');const [note,setNote]=useState('');const [error,setError]=useState('');const [dragging,setDragging]=useState(false);const input=useRef(null);return <div className="source-intake"><section className="upload-area"><div className="section-title"><h2>Add a record</h2><span className="muted small">Uploaded originals stay unchanged</span></div><label className={`drop-zone ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);setFiles(Array.from(e.dataTransfer.files));setError('')}}><input ref={input} type="file" multiple accept=".txt,.md,.csv,.pdf,.png,.jpg,.jpeg" onChange={e=>{setFiles(Array.from(e.target.files));setError('')}}/><span className="upload-icon"><Icon name="upload" size={25}/></span><strong>Choose files or drop them here</strong><span>Text, CSV, PDF, PNG or JPEG</span><small>Up to 12 files; 12 MB each. Scanned text needs a careful check.</small></label>{files.length>0&&<div className="pending-files">{files.map((f,i)=><div key={`${f.name}-${i}`}><Icon name="file"/><span>{f.name}</span><small>{(f.size/1024).toFixed(0)} KB</small><button type="button" className="icon-button" aria-label={`Remove ${f.name}`} onClick={()=>setFiles(v=>v.filter((_,j)=>j!==i))}><Icon name="close" size={15}/></button></div>)}</div>}<div className="upload-options"><label className="field"><span>Record type</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="evidence">Evidence or employer response</option><option value="filed-original">Copy of the filed original</option></select></label><button className="button" disabled={!files.length||busy} onClick={async()=>{setError('');try{await onUpload(files,kind);setFiles([]);if(input.current)input.current.value=''}catch(e){setError(e.message)}}}><Icon name="upload"/>{uploading?'Adding…':'Add files'}</button></div></section><section className="note-area"><h2>Add your account</h2><p className="muted">No written reply? Record what was said, who said it and when. Estimates are welcome when labelled.</p><form onSubmit={async e=>{e.preventDefault();setError('');try{await onNote(noteTitle,note);setNote('')}catch(e){setError(e.message)}}}><label className="field"><span>Note title</span><input required value={noteTitle} onChange={e=>setNoteTitle(e.target.value)}/></label><label className="field"><span>Your attributed account</span><textarea required rows="5" value={note} onChange={e=>setNote(e.target.value)} placeholder="On September 18, payroll told me…"/></label><button className="button secondary" disabled={busy||!note.trim()}><Icon name="plus"/>Save account</button></form></section>{error&&<ErrorBox message={error}/>}</div>}
export default function App(){
 const [cases,setCases]=useState([]);const [examples,setExamples]=useState([]);const [health,setHealth]=useState(null);const [preparedExample,setPreparedExample]=useState(null);const [preparedError,setPreparedError]=useState(false);const [activeId,setActiveId]=useState(caseFromHash);const [record,setRecord]=useState(null);const [tab,setTab]=useState(tabFromHash);const [selectedRevisionId,setSelectedRevisionId]=useState(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [toast,setToast]=useState('');const [modal,setModal]=useState(null);const [sourceView,setSourceView]=useState(null);const [paymentDecision,setPaymentDecision]=useState(null);const [job,setJob]=useState(null);const [railOpen,setRailOpen]=useState(false);const [listError,setListError]=useState('');
 const [requestState,setRequestState]=useState({data:null,loading:false,error:''});const [requestSelection,setRequestSelection]=useState(null);const requestSequence=useRef(0);const requestOpenSequence=useRef(0);const requestGuard=useRef(null);const priorHash=useRef(window.location.hash);
 const refreshPrepared=useCallback(async()=>{setPreparedError(false);setPreparedExample(null);try{setPreparedExample(await api('/prepared-example'))}catch{setPreparedError(true)}},[]);
 const refreshHealth=useCallback(async()=>{try{setHealth(await api('/health'))}catch{setHealth(null)}},[]);
 const refreshList=useCallback(async()=>{try{const data=await api('/cases');setCases(data.cases);setListError('')}catch(e){setListError(e.message)}},[]);
 const fetchCase=useCallback(async(id)=>{const result=await api(`/cases/${id}`);setRecord(result);return result},[]);
 useEffect(()=>{Promise.allSettled([refreshList(),api('/examples').then(x=>setExamples(x.examples)),refreshHealth(),refreshPrepared()]).then(()=>setLoading(false));const handle=()=>{if(requestGuard.current&&!requestGuard.current()){window.history.replaceState(null,'',priorHash.current);return;}priorHash.current=window.location.hash;setRequestSelection(null);setActiveId(caseFromHash());setSelectedRevisionId(null);setTab(tabFromHash());setError('');setRailOpen(false);setModal(null);setPaymentDecision(null);setSourceView(null)};window.addEventListener('hashchange',handle);return()=>window.removeEventListener('hashchange',handle)},[]);
 useEffect(()=>{if(!activeId){setRecord(null);setJob(null);return}let alive=true;setLoading(true);setRecord(null);setJob(null);api(`/cases/${activeId}`).then(r=>{if(alive){setRecord(r);setError('');refreshList();if(!r.readOnly&&(r.activeJobId||r.lastJobId))api(`/jobs/${r.activeJobId||r.lastJobId}`).then(x=>{if(!alive)return;setJob(x.job);if(x.job.status==='failed')setError(x.job.error?.message||x.job.error||x.job.message||'The latest analysis did not complete. Your sources are preserved; retry when ready.');if(x.job.status==='cancelled')setToast('The latest analysis was cancelled. Your sources are preserved.')}).catch(()=>{})}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[activeId]);
 useEffect(()=>{if(!job||!['running','queued'].includes(job.status))return;let alive=true;const timer=setTimeout(async()=>{try{const result=await api(`/jobs/${job.id}`);if(!alive)return;setJob(result.job);if(result.job.status==='completed'){await fetchCase(job.caseId);await refreshList();setError('');setToast('A new proposed account is ready to review.');setSelectedRevisionId(null);setTab('review')}if(['failed','cancelled'].includes(result.job.status)){await fetchCase(job.caseId);await refreshList();}if(result.job.status==='failed')setError(result.job.error?.message||result.job.error||'Analysis did not complete. Your records and previous account are preserved.')}catch(e){if(alive){setError(`Could not read analysis progress. Retrying automatically. ${e.message}`);setJob(j=>({...j,pollRetryAt:Date.now()}))}}},1500);return()=>{alive=false;clearTimeout(timer)}},[job,activeId]);
 useEffect(()=>{document.querySelector('.case-heading')?.scrollIntoView({block:'start'})},[tab,activeId]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5500);return()=>clearTimeout(t)},[toast]);


 const navigate=(id,view)=>{if(!id){refreshList();window.scrollTo(0,0);}window.location.hash=id?`/case/${id}${view?'?view='+view:''}`:'/';if(id===activeId)setRailOpen(false)};
 const accept=async(result,message)=>{setRecord(result);await refreshList();if(message)setToast(message);return result};
 const mutate=async(name,fn)=>{if(record?.readOnly&&!['create','example'].includes(name)){const e=new Error('This prepared example preserves a recorded run. Start a separate workspace to make changes.');setError(e.message);throw e}setBusy(name);setError('');try{return await fn()}catch(e){if(e.status===409){await fetchCase(activeId);await refreshList();setError('This case changed since you opened it. The latest version is loaded. Check it before trying again.')}else setError(e.message);throw e}finally{setBusy('')}};
 const current=record?.revisions.find(r=>r.id===record.currentRevisionId)||record?.revisions.at(-1);const revision=record?.revisions.find(r=>r.id===selectedRevisionId)||current;const historical=!!revision&&revision.id!==current?.id;const stale=!!current&&record?.sources.some(s=>!current.sourceIds?.includes(s.id));const running=job&&['queued','running'].includes(job.status);const disabled=!!busy||!!running;
 const readOnly=record?.readOnly===true;const modelMissing=health?.provider?.available===false;
 const refreshRequests=useCallback(async(override)=>{const requestCaseId=override?.caseId||record?.id;const requestRevisionId=override?.revisionId||revision?.id;const sequence=++requestSequence.current;if(!requestCaseId||!requestRevisionId){setRequestState({data:null,loading:false,error:''});return}setRequestState(old=>({...old,loading:true,error:''}));try{const data=await api(`/cases/${requestCaseId}/request-drafts?${new URLSearchParams({revision:requestRevisionId})}`);if(sequence===requestSequence.current)setRequestState({data,loading:false,error:''});return data}catch(e){if(sequence===requestSequence.current)setRequestState(old=>({...old,loading:false,error:e.message}));}},[record?.id,revision?.id]);
 useEffect(()=>{refreshRequests();},[refreshRequests,record?.version]);
 const openRequest=selection=>setRequestSelection({...selection,key:++requestOpenSequence.current});
 const saveRequest=async body=>{try{const result=await post(`/cases/${record.id}/request-drafts`,body);await accept(result.case);await refreshRequests({caseId:result.case.id,revisionId:selectedRevisionId||result.case.currentRevisionId});return result}catch(e){if(e.status===409){const latest=await fetchCase(record.id);await refreshList();await refreshRequests({caseId:latest.id,revisionId:selectedRevisionId||latest.currentRevisionId})}throw e}};

 const modelNotice=modelMissing?'Codex CLI is not available on this computer. You can inspect saved results now; configure Codex before running a new analysis.':health?.provider?'Codex CLI is detected. New analysis needs working model access; this local check has not verified a live request.':'Model setup could not be checked. Inspecting saved results does not need model access.';
 const analyze=()=>{if(modelMissing){setError('Codex CLI is not available. Your records are preserved. Configure the existing Codex setup, then check the local service again.');return}return mutate('analyze',async()=>{const result=await post(`/cases/${record.id}/analyze`,{expectedVersion:record.version});setJob(result.job);await refreshList();setTab('review')}).catch(()=>{})};
 const openSource=async(id,citation=null,context=null)=>{try{const source=await api(`/cases/${record.id}/sources/${id}`);setSourceView({source,citation,context,caseId:record.id})}catch(e){setError(e.message)}};
 const example=examples.find(e=>e.id===record?.exampleId);const nextPhases=(example?.phases.filter(p=>!record.importedPhases?.includes(p.id))||[]).slice(0,1);
 return <div className={`app ${activeId?'case-app':'home-app'}`}><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content').focus()}}>Skip to main content</a>
 <header className="site-header"><Logo onClick={()=>navigate(null)}/><nav className="primary-navigation" aria-label="Main navigation"><button className={!activeId?'active':''} onClick={()=>navigate(null)}>Case desk</button><button aria-expanded={railOpen} aria-haspopup="dialog" onClick={()=>setRailOpen(!railOpen)}>Switch case<Icon name="down" size={14}/></button></nav><div className="header-end"><span className="local-status"><span className="status-dot"/>Local workspace</span><button className="button header-create" onClick={()=>setModal('create')}><Icon name="plus" size={17}/>New case</button></div></header>
 {railOpen&&<Dialog title="Your workspaces" className="case-switcher-dialog" onClose={()=>setRailOpen(false)}><nav className="case-navigation" aria-label="Case workspaces">{cases.map(c=><button className={`case-nav-item ${c.id===activeId?'active':''}`} key={c.id} onClick={()=>{setRailOpen(false);navigate(c.id)}}><Icon name="folder"/><span><strong>{c.title}</strong>{c.unavailable?<small>Needs recovery · {c.message||'The saved case cannot be read. Original files are preserved.'}</small>:<><small>{c.exampleId?'Fictional workspace · ':''}{c.sourceCount} {c.sourceCount===1?'record':'records'} · {c.reviewed?'Reviewed':c.revisionCount?'Needs review':'Getting started'}</small><small>{workspaceSavedLabel(c,cases)}</small></>}</span>{c.id===activeId&&<Icon name="check" size={16}/>}</button>)}{!cases.length&&<p className="rail-empty">Create a case to start collecting your records.</p>}</nav><div className="dialog-footer"><button className="button" onClick={()=>{setRailOpen(false);setModal('create')}}><Icon name="plus"/>Create a case</button></div></Dialog>}

 <div className="app-body">{activeId&&<div className="topbar"><button className="breadcrumb-home" onClick={()=>navigate(null)}>Case desk</button><Icon name="chevron" size={13}/><span className="breadcrumb-current">{record?.title||(loading?'Opening case':'Case unavailable')}</span></div>}
 <main id="main-content" tabIndex="-1">{!activeId?<HomeDesk cases={cases} loading={loading} busy={busy} hasExample={!!examples[0]} preparedExample={preparedExample} preparedError={preparedError} onPreparedRetry={refreshPrepared} onPrepared={()=>navigate(preparedExample.caseId)} modelNotice={modelNotice} onCreate={()=>setModal('create')} onOpen={navigate} onRefresh={refreshList} error={error} listError={listError} onDismiss={()=>setError('')} onExample={()=>mutate('example',async()=>{const r=await post(`/examples/${examples[0].id}/start`);await accept(r);navigate(r.id)}).catch(()=>{})}/>:loading?<div className="page-loading"><span className="spinner"/><h2>Opening your case…</h2></div>:!record?<ErrorBox message={error||'This case could not be found.'} onRetry={()=>fetchCase(activeId).then(()=>setError('')).catch(e=>setError(e.message))}/>:<>
 <section className="case-heading"><div><div className="case-context-line">{record.exampleId&&<Badge>Fictional demonstration</Badge>}<span>{(revision?.analysis?revision.analysis.caseContext?.employerName:record.context?.employer)||'Employer not yet named'}</span><span>{claimStageLabel(record,revision)}</span></div><h1>{record.title}</h1><p>{record.sources.length} source {record.sources.length===1?'record':'records'}<span>•</span>{record.revisions.length} {record.revisions.length===1?'revision':'revisions'}<span>•</span>Saved {dateTime(record.updatedAt)}</p></div><div className="case-header-actions">{!readOnly&&<button className="button secondary" onClick={()=>setTab('sources')}><Icon name="plus"/>Add evidence</button>}{current&&<button className="button" onClick={()=>setTab('supplement')}><Icon name="download"/>Prepare update</button>}</div></section>
 {readOnly&&<section className="prepared-case-note" aria-label="About this prepared example"><div><span className="eyebrow">Prepared example · read only</span><h2>A recorded run, open for inspection.</h2><p>These are saved model results from a fictional demonstration, not a new analysis. Open sources, compare versions and prepare an example download. Editing and new analysis belong in a separate workspace.</p>{record.preparedExample?.reviewMeaning&&<p className="small muted">{record.preparedExample.reviewMeaning}</p>}<p className="small muted">{record.preparedExample?.label||'Fictional demonstration'} · recorded {dateTime(record.preparedExample?.recordedAt)}{record.preparedExample?.sourceRelease?` · ${record.preparedExample.sourceRelease}`:''}</p></div><button type="button" className="text-button" onClick={()=>navigate(null)}>Choose a fresh workspace<Icon name="arrow" size={16}/></button></section>}
 {!readOnly&&modelMissing&&<div className="notice model-setup-note" role="status"><Icon name="info"/><div><strong>New analysis needs Codex setup</strong><p>{modelNotice} You can still add records, inspect existing accounts and prepare downloads.</p><button type="button" className="text-button" onClick={refreshHealth}>Check local service again</button></div></div>}
 {error&&<ErrorBox message={error} onDismiss={()=>setError('')}/>}<div className="case-tabs" role="tablist" aria-label="Case view">{[['review','Case review','book'],['sources','Source records','file'],['history','Version history','history'],['supplement','Prepare update','download']].map(([id,label,icon])=><button key={id} id={`tab-${id}`} role="tab" tabIndex={tab===id?0:-1} aria-controls="case-panel" aria-selected={tab===id} onKeyDown={e=>{const ids=['review','sources','history','supplement'];let next=null;if(e.key==='ArrowRight')next=ids[(ids.indexOf(id)+1)%ids.length];if(e.key==='ArrowLeft')next=ids[(ids.indexOf(id)+ids.length-1)%ids.length];if(e.key==='Home')next=ids[0];if(e.key==='End')next=ids.at(-1);if(next){e.preventDefault();setTab(next);document.getElementById(`tab-${next}`)?.focus()}}} className={tab===id?'selected':''} onClick={()=>setTab(id)}><Icon name={icon} size={17}/>{label}{id==='sources'&&<span>{record.sources.length}</span>}</button>)}</div>
 {!readOnly&&record.sources.length>0&&!running&&(tab==='sources'||!current||stale||revision?.correctionNotice)&&<p className="analysis-boundary"><Icon name="lock" size={14}/>Choosing Analyze sends extracted source text to the configured model service. Use fictional records for this demonstration.</p>}
 {running&&<div className="analysis-progress" role="status"><span className="spinner"/><div><strong>{job.stage?words(job.stage):'Reading and reconciling the records'}</strong><p>{job.message||'Building a source-bound proposal. Your existing reviewed account remains intact.'}</p></div><button className="text-button" onClick={()=>post(`/jobs/${job.id}/cancel`).then(async x=>{setJob(x.job);await fetchCase(record.id);await refreshList();setToast('Analysis cancelled. Your records are preserved.');}).catch(e=>setError(e.message))}>Cancel analysis</button></div>}
 {!readOnly&&!running&&stale&&<div className="notice update-notice"><Icon name="file"/><div><strong>New records need a fresh review</strong><p>The account below does not yet include all current sources. Analyze them to propose an updated account.</p></div><button className="button" disabled={!!busy||modelMissing} onClick={analyze}>Analyze new records<Icon name="arrow"/></button></div>}
 {!readOnly&&!running&&!current&&record.sources.length>0&&tab!=='review'&&<div className="notice update-notice"><Icon name="book"/><div><strong>Your sources are ready</strong><p>Analysis proposes the first account from these records.</p></div><button className="button" disabled={!!busy||modelMissing} onClick={analyze}>Analyze records<Icon name="arrow"/></button></div>}
 {historical&&<div className="notice history-notice"><Icon name="history"/><div>Viewing revision {revision.number}. This is a preserved historical account.</div><button className="text-button" onClick={()=>setSelectedRevisionId(null)}>Return to current revision</button></div>}
 {!readOnly&&!historical&&revision?.correctionNotice&&<div className="notice correction-notice"><Icon name="info"/><div><strong>Related interpretations need a fresh look</strong><p>{revision.correctionNotice.message}</p></div><button className="button secondary" disabled={disabled||modelMissing} onClick={analyze}>Analyze the updated account<Icon name="refresh" size={15}/></button></div>}
 <div id="case-panel" role="tabpanel" aria-labelledby={`tab-${tab}`}>
 {tab==='review'&&<CaseOverview caseRecord={record} revision={revision} previous={record.revisions.at(-2)} sources={record.sources} onSource={openSource} onEdit={()=>setModal('edit')} onReview={()=>setModal('review')} onAnalyze={analyze} onPrepare={()=>setTab('supplement')} onPayment={(paymentId,topic)=>setPaymentDecision({paymentId,topic})} busy={disabled} stale={stale} historical={historical} readOnly={readOnly} analysisUnavailable={modelMissing} requestState={requestState} onRequest={openRequest} onRequestRefresh={refreshRequests}/>}
 {tab==='sources'&&<>{!readOnly&&<RecordUpload caseRecord={record} busy={disabled} uploading={busy==='upload'} onUpload={(files,kind)=>mutate('upload',async()=>{const body=new FormData();files.forEach(f=>body.append('files',f));body.append('kind',kind);body.append('expectedVersion',record.version);return accept(await api(`/cases/${record.id}/sources`,{method:'POST',body}),'Records added. Analyze them when you are ready.')})} onNote={(title,text)=>mutate('note',async()=>accept(await post(`/cases/${record.id}/notes`,{title,text,kind:'worker-account',expectedVersion:record.version}),'Your account was saved as an attributed source.'))}/>}<section className="document-section source-register"><div className="section-title"><h2>The source record</h2>{!readOnly&&<button className="text-button" disabled={!record.sources.length||disabled||modelMissing} onClick={analyze}><Icon name="refresh" size={14}/>Analyze records</button>}</div>{record.sources.length?record.sources.map((s,i)=><div className="source-register-row" key={s.id}><div className="source-number">{String(i+1).padStart(2,'0')}</div><Icon name="file"/><button className="source-open" onClick={event=>{event.currentTarget.focus();openSource(s.id)}}><strong>{s.name}</strong><span>{words(s.kind)} · {s.lineCount||s.text?.split('\n').length||0} lines · {s.extraction?.method||'Text'}</span>{s.extraction?.warnings?.length>0&&<small className="warning-text">Check extracted text</small>}</button><a className="icon-button" href={`/api/cases/${record.id}/sources/${s.id}/file`} download aria-label={`Download original ${s.name}`}><Icon name="download"/></a><button className="icon-button" aria-label={`Read ${s.name}`} onClick={()=>openSource(s.id)}><Icon name="chevron"/></button></div>):<p className="empty-note">No records yet. Add a file or your account above.</p>}</section>{!readOnly&&nextPhases.length>0&&<section className="example-next"><div><Badge>Fictional example</Badge><h3>Continue the case with new evidence</h3><p>Import the next raw records, then analyze what changed. Each phase adds sources to this same case.</p></div><div>{nextPhases.map(p=><button key={p.id} className="button secondary" disabled={disabled} onClick={()=>mutate('phase',async()=>accept(await post(`/cases/${record.id}/example-phase`,{phaseId:p.id,expectedVersion:record.version}),'The next example records are ready to analyze.')).catch(()=>{})}>Add {p.label}<Icon name="plus"/></button>)}</div></section>}</>}
 {tab==='history'&&<section className="history-view"><h2>Every account keeps its place</h2><p className="muted">The original sources and previous versions stay available. A fresh proposal always needs its own review.</p>{record.revisions.length?<div className="version-list">{[...record.revisions].reverse().map(r=><article className="version-row" key={r.id}><div className={`version-node ${isReviewed(r)?'reviewed':''}`}><Icon name={isReviewed(r)?'check':'history'} size={16}/></div><div><div className="section-title"><h3>Revision {r.number}{r.id===current?.id&&<Badge>Current</Badge>}</h3><Badge tone={isReviewed(r)?'good':'attention'}>{isReviewed(r)?'Reviewed':'Draft'}</Badge></div><p>{r.analysis.summary}</p><div className="version-meta"><span>{dateTime(r.createdAt)}</span><span>{r.origin==='user'?'Your correction':'Model proposal'}</span><strong>{moneyRange((r.calculation||r.reconciliation)?.totals?.differenceMinCents,(r.calculation||r.reconciliation)?.totals?.differenceMaxCents)}</strong></div>{r.reason&&<p className="small muted">{r.reason}</p>}<button className="text-button" onClick={()=>{setSelectedRevisionId(r.id);setTab('review')}}>Inspect this account<Icon name="arrow" size={15}/></button></div></article>)}</div>:<Empty title="No revisions yet" icon="history">Analyze your sources to create the first proposed account.</Empty>}</section>}
 {tab==='supplement'&&(revision?<PrepareUpdate key={`${revision.id}-${record.version}`} caseRecord={record} revision={revision} stale={stale} historical={historical} readOnly={readOnly} onEditDetails={()=>setModal('edit')} onSource={openSource}/>:<Empty title="An update starts with the facts" icon="file">Add the records or your account, then analyze them. An incomplete work account can still support a factual payment update.</Empty>)}
 </div><footer className="case-footer"><span><Icon name="lock" size={14}/>Stored locally. Analysis uses the configured model service.</span><span>Factual support for your review; no filing or settlement action.</span></footer></>}
 <details className="local-diagnostics"><summary>About this local workspace</summary><p>WageProof prepares factual updates for review. Files and case state stay on this computer. Analysis sends extracted text to the configured model service; inference is not offline.</p>{health?.build?<dl><div><dt>Running build</dt><dd>{health.build.label}</dd></div><div><dt>Started</dt><dd>{dateTime(health.build.startedAt)}</dd></div><div><dt>Source hash</dt><dd><code>{health.build.sourceSha256||'Not recorded'}</code></dd></div><div><dt>Data directory</dt><dd><code>{health.build.dataDirectory}</code></dd></div><div><dt>Interface directory</dt><dd><code>{health.build.distDirectory}</code></dd></div></dl>:<p>Build details could not be loaded.</p>}<p>{modelNotice}</p><button type="button" className="text-button" onClick={refreshHealth}>Check local service again</button><p>Identity is observed at server startup. Rebuilding interface files afterward does not refresh this recorded identity. {health?.provider?.authenticationCheck}</p></details>
 </main></div>{toast&&<div className="toast" role="status"><Icon name="check"/>{toast}</div>}{modal==='create'&&<CreateCase busy={!!busy} onClose={()=>setModal(null)} onCreate={body=>mutate('create',async()=>{const r=await post('/cases',body);await accept(r);setModal(null);navigate(r.id,'sources')})}/>} {!readOnly&&modal==='edit'&&revision&&<ReviewEditor analysis={revision.analysis} busy={!!busy} onClose={()=>setModal(null)} onSave={(analysis,reason)=>mutate('correction',async()=>{const result=await post(`/cases/${record.id}/revisions`,{analysis,reason,expectedVersion:record.version});await accept(result,result.currentRevisionId===record.currentRevisionId?'No account changes to save. The current revision is unchanged.':'Corrected draft saved. Review this new account before using it.');setSelectedRevisionId(null);setModal(null)})}/>} {!readOnly&&modal==='review'&&revision&&<ReviewConfirm revision={revision} busy={!!busy} onClose={()=>setModal(null)} onConfirm={note=>mutate('review',async()=>{await accept(await post(`/cases/${record.id}/review`,{revisionId:revision.id,expectedVersion:record.version,note}),'This account is reviewed. The update is ready to prepare.');setModal(null);setTab('supplement')})}/>} {!readOnly&&paymentDecision&&revision&&<PaymentDecision key={`${revision.id}-${paymentDecision.paymentId}`} analysis={revision.analysis} paymentId={paymentDecision.paymentId} initialTopic={paymentDecision.topic} sources={record.sources} onSource={openSource} busy={!!busy} onClose={()=>setPaymentDecision(null)} onFullEditor={()=>{setPaymentDecision(null);setModal('edit')}} onSave={(analysis,reason)=>mutate('correction',async()=>{const result=await post(`/cases/${record.id}/revisions`,{analysis,reason,expectedVersion:record.version});await accept(result,result.currentRevisionId===record.currentRevisionId?'No account changes to save. The current revision is unchanged.':'Correction saved as a new draft. Review the changed account.');setSelectedRevisionId(null);setPaymentDecision(null);setTab('review')})}/>} {requestSelection&&requestState.data&&record&&<RequestDraftDialog key={requestSelection.key} caseRecord={record} selection={requestSelection} index={requestState.data} onSave={saveRequest} onRefresh={refreshRequests} onSource={openSource} onClose={()=>setRequestSelection(null)} onStartCurrent={actionId=>openRequest({actionId})} onCurrentAccount={async()=>{setRequestSelection(null);setSelectedRevisionId(null);setTab('review');try{await fetchCase(record.id);await refreshList()}catch(e){setError(e.message)}}} navigationGuard={requestGuard}/>} {sourceView&&<SourceDrawer {...sourceView} onClose={()=>setSourceView(null)}/>}</div>
}
